apiVersion: v1
kind: Pod
metadata: 
  name: empty
spec:
  container:
    image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  container:
    image: almalinux:9
    name: almalinux
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
      readOnly: true
volumes:
- name: nginx-logs
  emptyDir: 
    sizeLimit: 500Mi