apiVersion: v1
kind: pod
metadata: 
  name: empty
spec:
  containers:
    image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  containers:
    image: almalinux:9
    name: almalinux
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
      readOnly: true
volumes:
- name: nginx-logs
  emptyDir: 
    sizeLimit: 500Mi