apiVersion: v1
kind: ReplicaSet
metadata:
  name: nginx-ReplicaSet
  labels:
    project: roboshop
    environment: dev
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: frontend
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx